=== oalam/cours/com.oalam.xml/src/ressources/messages.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/note.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE messages SYSTEM "note.dtd">

    <messages>
    ...
    </messages>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT messages (note)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT note (to,from,heading,body)>
<!ATTLIST note
    id CDATA #REQUIRED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT to (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT from (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT heading (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT body (#PCDATA)>

=== oalam/cours/com.oalam.xml/src/ressources/messages.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--

<!DOCTYPE messages SYSTEM "messages.dtd">

-->
<messages xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="messages.xsd">

    <note id="501"  lang="l">
         <from>Jani</from>
        <to>Tove</to>
       
        <heading>Reminder</heading>
        <body>Don't forget me this weekend!</body>

    </note>
    <note id="502">
        <to>Jani</to>
        <from>Tove</from>
        <heading>Re: Reminder</heading>
        <body>I will not</body>
    </note>

</messages>
