=== oalam/cours/JavaSE-cours/src/xml/bookstore.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 (http://www.altova.com) by plouk (plik) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="bookstore">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="book" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="isbn" type="xs:string"/>
							<xs:element name="title" type="xs:string"/>
							<xs:element name="page_count"/>
							<xs:element name="author" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="name"/>
									</xs:sequence>
									<xs:attribute name="id" type="xs:short"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== oalam/cours/JavaSE-cours/src/xml/bookstore.xml
<?xml version="1.0" encoding="UTF-8"?>
<bookstore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/workspace/formation-java/JavaSE-cours/src/xml/bookstore.xsd">
	<book>
		<isbn/>
		<title/>
		<page_count/>
		<author id="2">
			<name/>
		</author>
	</book>
	<book>
		<isbn></isbn>
		<title></title>
		<page_count></page_count>
		<author>
			<name></name>
		</author>
	</book>
</bookstore>
