=== oalam/cours/xml/src/xml/ressources/bookstore.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2012 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="ST_title">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Everyday Italian"/>
			<xs:enumeration value="Harry Potter"/>
			<xs:enumeration value="Learning XML"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="year">
		<xs:simpleType>
			<xs:restriction base="xs:short">
				<xs:enumeration value="2003"/>
				<xs:enumeration value="2005"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="title">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="ST_title">
					<xs:attribute name="lang" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="en"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="price2">
		<xs:simpleType>
			<xs:restriction base="xs:decimal">
				<xs:enumeration value="30.0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="price">
		<xs:simpleType>
			<xs:restriction base="xs:decimal">
				<xs:enumeration value="29.99"/>
				<xs:enumeration value="30.0"/>
				<xs:enumeration value="39.95"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="bookstore">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="book" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="book">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="title"/>
				<xs:element ref="author"/>
				<xs:element ref="year"/>
				<xs:element ref="price"/>
				<xs:element ref="price2" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="category" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="CHILDREN"/>
						<xs:enumeration value="COOKING"/>
						<xs:enumeration value="WEB"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="author">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Erik T. Ray"/>
				<xs:enumeration value="Giada De Laurentiis"/>
				<xs:enumeration value="J K. Rowling"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== oalam/cours/xml/src/com/steria/bookstore/xml/newXMLDocument1.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : newXMLDocument1.xml
    Created on : June 26, 2012, 9:20 PM
    Author     : tom
    Description:
        Purpose of the document follows.
-->

<ns1:bookstore  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns1='null'
   xsi:schemaLocation='null file:/Users/tom/Documents/workspace/formation-cours/xml/src/xml/ressources/bookstore.xsd'>
    <book category="">
	<title lang=""></title>
	<author></author>
	<year></year>
	<price></price>
	<price2></price2>
    </book>
    <book category="">
	<title lang=""></title>
	<author></author>
	<year></year>
	<price></price>
	<price2></price2>
    </book>
    <book category="">
	<title lang=""></title>
	<author></author>
	<year></year>
	<price></price>
	<price2></price2>
    </book>

</ns1:bookstore>
