<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE NEWSPAPER [

<!ELEMENT NEWSPAPER (ARTICLE+)>
<!ELEMENT ARTICLE (HEADLINE,BYLINE,LEAD,BODY,NOTES)>
<!ELEMENT HEADLINE (#PCDATA)>
<!ELEMENT BYLINE (#PCDATA)>
<!ELEMENT LEAD (#PCDATA)>
<!ELEMENT BODY (#PCDATA)>
<!ELEMENT NOTES (#PCDATA)> 

<!ATTLIST ARTICLE AUTHOR CDATA #REQUIRED>
<!ATTLIST ARTICLE EDITOR CDATA #IMPLIED>
<!ATTLIST ARTICLE DATE CDATA #IMPLIED>
<!ATTLIST ARTICLE EDITION CDATA #IMPLIED>

]>

<NEWSPAPER>
    <ARTICLE AUTHOR="tom"  DATE="11/11/11" EDITION="gold">
        <HEADLINE>news</HEADLINE>
        <BYLINE>from paris</BYLINE>
        <LEAD>plik </LEAD>
        <BODY>plok</BODY>
        <NOTES>plak</NOTES>  
         
    </ARTICLE>

</NEWSPAPER>
