=== oalam/cours/xml/src/xml/ressources/order.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Customer" type="Customer"/>
	<xs:complexType name="Customer">
		<xs:sequence>
			<xs:element name="creditcard" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="email" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="Order" type="Order"/>
	<xs:complexType name="Order">
		<xs:sequence>
			<xs:element name="creationdate" type="xs:date" minOccurs="1" maxOccurs="1"/>
			<xs:element name="id" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<xs:element name="customer" type="Customer" minOccurs="1" maxOccurs="1"/>
			<xs:element name="status" type="ORDER_STATUS" minOccurs="1" maxOccurs="1"/>
			<xs:element name="orderedProducts" type="OrderedProduct" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="ORDER_STATUS">
		<xs:restriction base="xs:string">
			<xs:enumeration value="pending"/>
			<xs:enumeration value="canceled"/>
			<xs:enumeration value="shipped"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="OrderedProduct" type="OrderedProduct"/>
	<xs:complexType name="OrderedProduct">
		<xs:sequence>
			<xs:element name="productcount" type="xs:int" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== oalam/cours/xml/src/com/steria/bookstore/xml/newXMLDocument2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : newXMLDocument2.xml
    Created on : June 26, 2012, 9:42 PM
    Author     : tom
    Description:
        Purpose of the document follows.
-->

<ns1:Order  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns1='null'
   xsi:schemaLocation='null file:/Users/tom/Documents/workspace/formation-cours/xml/src/xml/ressources/order.xsd'>
    <creationdate></creationdate>
    <id></id>
    <customer>
	<creditcard></creditcard>
	<email></email>
	<name></name>
    </customer>
    <status></status>
    <orderedProducts>
	<productcount></productcount>
    </orderedProducts>
    <orderedProducts>
	<productcount></productcount>
    </orderedProducts>
    <orderedProducts>
	<productcount></productcount>
    </orderedProducts>

</ns1:Order>
